name: Tests CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test on ${{ matrix.os }} with Node.js version ${{ matrix.node_version }}

    strategy:
      matrix:
        node_version: ['8', '9', '10', '11', '12', '13']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          node_version: ${{ matrix.node_version }}
      - run: yarn
      - run: yarn bootstrap
      - run: yarn test
